[WIP] Dutchv3
Uniswap/uniswapx-service pull request #490
Opened 2024-11-20 15:22 UTC by codyborn

2024-11-22 09:21 UTC, alanhwu requested changes

2024-11-22 09:21 UTC, alanhwu commented on lib/util/OffChainUniswapXOrderValidator.ts
> +    if (orderType == OrderType.Dutch_V2 || orderType == OrderType.Dutch_V3) {
Should we also be validating the overrides of `inputOverride < input` and `outputOverride > output`?

2024-11-22 09:21 UTC, alanhwu commented on package.json
> +    "@uniswap/uniswapx-sdk": "^2.1.0-beta.20",
bump to 21

2024-11-22 09:21 UTC, alanhwu commented on test/unit/handlers/get-orders.test.ts
>      encodedOrder:
If this was previously an encoded V2 order, how do we use it as a V3?

2024-11-22 09:21 UTC, alanhwu commented on test/integ/handlers/check-order-status.test.ts
> +        const mockOrder = SDKDutchOrderV3Factory.buildDutchV3Order(ChainId.MAINNET, {
Maybe use arbitrum chainId for consistency

2024-11-22 09:21 UTC, alanhwu commented on test/unit/models/DutchV3Order.test.ts
> +    const order = new DutchV3Order(SDKDutchOrderV3Factory.buildDutchV3Order(), MOCK_SIGNATURE, ChainId.MAINNET)
Maybe use Arbitrum chainId for consistency

2024-11-22 09:21 UTC, alanhwu commented on test/unit/services/OrderDispatcher.test.ts
> +        params: new QueryParamsBuilder().withChainId(1).build(),
chainId 42161?

2024-11-25 12:21 UTC, codyborn commented on lib/entities/Order.ts
> +  startAmount?: string
Good catch. It's not necessary to be optional.

2024-11-25 12:31 UTC, codyborn commented on lib/repositories/dutch-orders-repository.ts
> +        decayStartBlock: { type: DYNAMODB_TYPES.NUMBER },
I don't think so. All these fields are stored in the `encodedOrder` so this just contains columns that we may wish to query on.

2024-11-25 12:40 UTC, codyborn commented on lib/models/DutchV3Order.ts
> +    readonly inner: SDKV3DutchOrder,
I think inner is usually used in objects that wrap some kind of inner object. It could be used for a cosigned wrapper, but in this case it's the database object.

2024-11-25 12:52 UTC, codyborn commented on test/unit/handlers/get-orders.test.ts
>      encodedOrder:
The test that's using this doesn't deserialize it. It just uses the object as a placeholder for a possible V3 value.

2024-11-27 09:03 UTC, alanhwu approved these changes

2024-11-27 09:39 UTC, alanhwu commented on lib/handlers/check-order-status/util.ts
> +    (parsedOrder.info.input.curve.relativeAmounts.length === 1 ||
should it be `(parsedOrder.info.input.curve.relativeAmounts.length === 1 && 
    parsedOrder.info.input.curve.relativeAmounts[0] === BigInt(0))`?

2024-12-02 07:36 UTC, merged